Test1.2:"Complex Numbers"
Naveen-2611/Training pull request #11
Opened 2024-12-13 11:39 UTC by Naveen-2611

2024-12-17 05:50 UTC, Dakshita-Minocha requested changes

2024-12-17 05:50 UTC, Dakshita-Minocha commented on Project21/Project21/comp.c
> +   return output;
Initial values for variables need not be Zero. You can directly use your desired values. Similarly fix everywhere.
```suggestion
   Complex output = {  c1.Realpart + c2.Realpart, c1.Imagpart + c2.Imagpart };
   return output;
```

2024-12-17 05:50 UTC, Dakshita-Minocha commented on Project21/Project21/testcomp.c
> +   Complex Number1 = { 10.1f,12.7f }, Number2 = { 15.0f,8.7f };
Follow naming convention

2024-12-26 06:31 UTC, Dakshita-Minocha commented on Project21/Project21/comp.c
> +Complex Op_Add (Complex c1, Complex c2) {
Follow naming conventions
```suggestion
Complex OpAdd (Complex c1, Complex c2) {
```

2024-12-26 06:31 UTC, Dakshita-Minocha commented on Project21/Project21/comp.c
> +   Complex output = { c1.Realpart + c2.Realpart, c1.Imagpart + c2.Imagpart };
```suggestion
   Complex output = { c1.RealPart + c2.Realpart, c1.ImagPart + c2.Imagpart };
```

2024-12-26 06:31 UTC, Dakshita-Minocha commented on Project21/Project21/testcomp.c
> +   Complex Output1 = Op_Add (num1, num2);
Follow naming conventions.

2024-12-26 06:31 UTC, Dakshita-Minocha commented on Project21/Project21/testcomp.c
> +   printf (Output1.Imagpart == expOutputAdd.Imagpart && Output1.Realpart == expOutputAdd.Realpart ? "Addition:"ANSI_COLOR_GREEN"Passed\n" ANSI_COLOR_RESET : "Addition:Failed\n");
You should print pass/fail only once. Print "Pass" once the whole test has passed and "Fail" and exit the moment even one test fails.

2024-12-26 07:06 UTC, Dakshita-Minocha requested changes

2024-12-26 07:06 UTC, Dakshita-Minocha commented on Project21/Project21/Traingit.c
> +//   printf (ANSI_COLOR_RESET"Addition:"ANSI_COLOR_GREEN);
Remove unecessary comments

2024-12-31 04:54 UTC, gdineshkumar219 commented on Project21/Project21/testcomp.c
> +   if (Output1.ImagPart != expOutputAdd.ImagPart || Output1.RealPart != expOutputAdd.RealPart) {
Instead of checking this comparison for all operations better to do have a method for == as we use before for addition, subtraction

2025-01-02 03:21 UTC, gdineshkumar219 commented on Project21/Project21/testcomp.c
> +   Complex Output7 = Conjugate (B);
Follow naming conventions properly. Variable name should begin with lowercase letters.

2025-01-02 03:21 UTC, gdineshkumar219 commented on Project21/Project21/testcomp.c
> +}
In this you are comparing real parts and imaginary parts multiple times better to have a method `IsEqual() `similar to `OpAdd()`

2025-01-02 03:21 UTC, gdineshkumar219 commented on Project21/Project21/comp.h
> +#define ANSI_COLOR_RESET   "\x1b[0m"
These color codes should be in testComp.c

2025-01-02 03:21 UTC, gdineshkumar219 commented on Project21/Project21/comp.c
> +}
Don't use printing functions in class library

2025-01-02 03:21 UTC, gdineshkumar219 commented on Project21/Project21/testcomp.c
> +   Complex A = { 10.1f,12.7f }, B = { 15.0f,8.7f };
Test for more number of inputs

2025-01-06 11:23 UTC, Dakshita-Minocha commented on Project21/Project21/comp.c
> +   return a.ImagPart == b.ImagPart && a.RealPart == b.RealPart;
You should never directly compare 2 doubles. It is a very common source of errors.

2025-01-07 04:54 UTC, gdineshkumar219 commented on Project21/Project21/comp.c
> +  // return a.ImagPart == b.ImagPart && a.RealPart == b.RealPart;
remove commented lines

2025-01-07 06:42 UTC, Dakshita-Minocha approved these changes

2025-01-07 06:42 UTC, closed without merging