A4: Palindrome
Naveen-2611/Training pull request #5
Opened 2024-09-19 09:45 UTC by Naveen-2611

2024-09-19 12:22 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +// C program to Check the Palindrome or not
Give Proper description that justifies the whole assignment

2024-09-19 12:22 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   char* intResult = strchr (input, ch);
Directly compare with '\n' rather than having separate variable

2024-09-19 12:22 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   number = strtol (input, &endptr, 10);
Can directly declare and assign here no need for separate declaration as strtol method never returns a null value

2024-09-19 12:22 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   long long int rev = 0;
Give comment for using long long int data type

2024-09-20 11:17 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   char* strResult = strchr (sentences, ch);
Here also you can directly use '\n' instead of having a variable, look for similar corrections in whole code, if a correction is given

2024-09-20 11:17 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +/// <summary>Functions to check the given number is palindrome or not </summary>
There is no multiple function or method, so have it in singular, look for similar corrections

2024-09-20 11:17 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   if (num < 0) {
Negative numbers can also be reversed, but they are not palindrome, so it should not be considered invalid. Change accordingly to handle negative integers too

2024-09-23 11:32 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   if (j != NULL && sentences[0] != '\n' && strResult != NULL) {
Brackets are not necessary

2024-09-24 11:42 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   int number = strtol (input, &endptr, 10);
The method fails to take the last digit if it is '0', e.g.: Input-0987890 should produce out as palindrome, but this implementation fails to achieve it.

2024-09-24 11:42 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   int numInput[] = { 0,89756,121,34543,7777,13487,-1,-111,123,12121 };
Add more test cases to check all possible errors.

2024-09-25 08:59 UTC, dineshN52 requested changes

2024-09-25 08:59 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +      if (num != 10) {
Instead use fgets() to get option

2024-09-25 08:59 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +// Copyright (c) Naveenkumar S @Metamation India.
Don't edit the comments here, you can give the description below the copyrights

2024-09-25 08:59 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   char* i = fgets (input, sizeof (input), stdin);
Declare similar data type variables in single line and check for similar corrections in the code

2024-09-25 08:59 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   if (intResult == NULL) ClrBuffer (option);
Add any test case which can cover this line of code and verify the below method is necessary.

2024-10-14 05:02 UTC, dineshN52 requested changes

2024-10-14 05:02 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +
There is no need for a line space

2024-10-14 05:02 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   char* strInput[] = { "Don't nod","Able was I ere I saw Elba", "racecar","Otto","Trumpf Metamation","RADAR","NASA","MALAYALAM","Kayak","LEVEL" };
The case Trumpf Metamation is not a palindrome, but it passes the test, Check for the failure

2024-10-14 05:02 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +      //printf ((NumberIsPalindrome (NumInput[i]) == true) ? " PASS\n" : " FAIL\n");
Remove the commented lines

2024-10-14 05:02 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +   char* i = fgets (input, sizeof (input), stdin);
Declaration of same data type can be in single line, check for similar corrections and update

2024-10-14 11:59 UTC, dineshN52 requested changes

2024-10-14 11:59 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +      printf ((result == strExpected[i]) ? " PASS\n" : " FAIL\n");
Give proper prompt, whether you're checking the output of the input or the test case passed the test

2024-10-23 04:50 UTC, dineshN52 requested changes

2024-10-23 04:50 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +      if (result == true) {
Can be implemented using ternary operator and look for similar corrections and update

2024-10-23 04:50 UTC, dineshN52 commented on Project21/Project21/Palindrome.c
> +      char* result = strchr (choice, '\n');
Declare similar data types in single line

2024-11-05 11:03 UTC, Dakshita-Minocha requested changes

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      printf ("Output: %-7lld   ", rev);
IsPalindrome should only return if an input is valid or not. Only the calling function should print.

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +bool NumberIsPalindrome (int num) {
When a function/method returns boolean, we name it as starting with 'Is'. (General coding convention)
```suggestion
bool IsPalindrome (int num) {

```

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   if (org < 0) {
This check is not required. You can use abs () from math.h

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   return (rev == org);
```suggestion
   return rev == org;

```

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      if (toupper (temp[n]) != toupper (temp[j - n - 1])) return false;
This check can be performed within the while loop. You do not need to parse the string twice.

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   else PrintResult (NumberIsPalindrome (number));
You can re-use your string palindrome function by passing the input string to it.
Also, since you are implementing different function behaviour based on input, you should look at compile-time polymorphism in C. C (and most other common languages) which allows you to declare function of the same name with different parameters.

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +void StringInput (int option) {
![image](https://github.com/user-attachments/assets/603d9936-5cf4-4705-abcf-b3e8477e909d)
Please consider making the changes as suggested by intellisense (wherever applicable).

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      output1 = (result == true) ? "palindrome" : "Not palindrome";
Result is of type boolean and the expression also evaluates boolean so you do not need to compare with true here.
```suggestion
      output1 = result ? "palindrome" : "Not palindrome";

```

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      printf ("Test Case%3d: Input--> %-28s ", i + 1, strInput[i]);
Since you are printing everything on the same line, it would be easier (and nicer) to read this code, if it were, similarly, in the same printf statement.

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   int NumInput[] = { 0,89756,121,34543,7777,13487,-1,-111,123,12121 };
It is recommended to have your tests/test functions separate for separate cases. Please consider the same review comments here as above.

2024-11-05 11:03 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +         while (getchar () != '\n');
Make this change wherever applicable.
```suggestion
      if (!result) while (getchar () != '\n');

```

2024-11-06 10:51 UTC, Dakshita-Minocha reviewed
Please remove rough work and unnecessary comments and re-assign

2024-11-11 06:05 UTC, Dakshita-Minocha requested changes

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +static bool StringIsPalindrome (char* sentences) {
Please look up function overloading and compile time polymorphism to understand this.
```suggestion
static bool IsPalindrome (char* sentences) {

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   return *rev == org;
```suggestion
   return abs (*rev) == org;

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +static void IntegerInput (int option) {
```suggestion
static void GetIntegerInput (int option) {

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +            StringInput (num);
Why is it required to pass this "option" param al the way to ClrBuffer from here?

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +static void StringInput (int option) {
```suggestion
static void GetStringInput (int option) {

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   char input[MAX_VALUE], * endptr, * intResult, * i;
What is i? Please name variables appropriately.

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   j = fgets (sentences, sizeof (sentences), stdin);
What is j? Please name variables appropriately.

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   char* NumExpected[] = { "palindrome","Not palindrome","palindrome","palindrome","palindrome","Not palindrome","Not palindrome","Not palindrome","Not palindrome","palindrome" };
Your output in some places is capitalized, and in some cases its not. You should try to make it as consistent as possible.
![image](https://github.com/user-attachments/assets/b23518e1-7369-4819-ab14-25c741b8c742)

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      output1 = (result) ? "palindrome" : "Not palindrome";
```suggestion
      output1 = result ? "palindrome" : "Not palindrome";

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   char* strExpected[] = { "palindrome","palindrome","palindrome","palindrome","Not palindrome","palindrome","Not palindrome","palindrome","palindrome","palindrome" };
Currently, you are converting StringIsPalindrome()'s Boolean output to string and then comparing that string. "Palindrome"/"Not Palindrome" is only relevant for printing output, not for comparison. Better to have the expected output as a Boolean and compare that then print accordingly.

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      output1 = (result) ? "palindrome" : "Not palindrome";
Also, try not to name variables as output1, output2. Even that, if necessary (in this case it is not - output is a local variable and there is no repetition happening, we name them as output, output2 and so on.

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   char* NumExpected[] = { "palindrome","Not palindrome","palindrome","palindrome","palindrome","Not palindrome","Not palindrome","Not palindrome","Not palindrome","palindrome" };
```suggestion
   char* numExpected[] = { "palindrome","Not palindrome","palindrome","palindrome","palindrome","Not palindrome","Not palindrome","Not palindrome","Not palindrome","palindrome" };

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +   int NumInput[] = { 0,89756,121,34543,7777,13487,-1,-111,123,12121 };
Please follow metamation conventions while naming variables
```suggestion
   int numInput[] = { 0,89756,121,34543,7777,13487,-1,-111,123,12121 };

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +static void NumberCheck () {
```suggestion
static void TestReversal() {

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +static void OutputCheck () {
The variable function names must reflect what function they perform in your code.
```suggestion
static void TestPalindrome() {

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      if (!result)while (getchar () != '\n');
```suggestion
      if (!result) while (getchar () != '\n');

```

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      printf ("%-30s%-20s", NumExpected[i], output);
Right now, you are not testing reversal at all (which is half your program). Better to do all the palindrome checks in one test function and have a separate function for reversal outputs (for eg: here, your expected output should be {0, 65798, ..}

2024-11-11 06:05 UTC, Dakshita-Minocha commented on Project21/Project21/Palindrome.c
> +      output = (result == true) ? "palindrome" : "Not palindrome";
```suggestion
      char* output = result ? "palindrome" : "Not palindrome";

```

2024-11-15 09:49 UTC, Dakshita-Minocha approved these changes

2024-11-15 09:49 UTC, closed without merging